blank_issues_enabled: true
contact_links:
  - name: STAR Support
    url: https://t.me/SUPP0RT_STAR
    about: Direct chat on non-inquiries subjects.
  - name: Documentation
    url: https://startech/
    about: Documentation for getting started with bot.
